# Generated by Django 3.2 on 2021-04-21 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orgcontact',
            options={'verbose_name': 'Organization Contact'},
        ),
        migrations.RenameField(
            model_name='orgcontact',
            old_name='linked_org',
            new_name='organization',
        ),
    ]
