# Generated by Django 3.2.2 on 2021-08-12 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('gig', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='gig',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gig.gig'),
        ),
    ]
