# Generated by Django 3.2 on 2021-04-21 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0002_auto_20210412_2245'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_in', models.DateTimeField()),
                ('time_out', models.DateTimeField()),
                ('processed', models.BooleanField(default=False)),
                ('contested', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('E', 'Estimate'), ('B', 'Booked'), ('A', 'Awaiting Payment'), ('C', 'Closed')], max_length=1)),
                ('payment_due', models.DateField()),
                ('paid', models.DateField()),
                ('fees', models.ManyToManyField(to='finance.Fee')),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gig.gig')),
            ],
        ),
    ]
