# Generated by Django 3.2.2 on 2021-05-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='status',
            field=models.CharField(choices=[('E', 'Estimate'), ('B', 'Booked'), ('A', 'Awaiting Payment (Show Concluded)'), ('C', 'Closed')], default='E', max_length=1),
        ),
    ]
