# Generated by Django 3.2 on 2021-04-13 02:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location', '0001_initial'),
        ('client', '0001_initial'),
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('load_in_lighting', models.DateTimeField(blank=True, null=True)),
                ('load_in_sound', models.DateTimeField(blank=True, null=True)),
                ('start', models.DateTimeField(verbose_name='Gig start time')),
                ('end', models.DateTimeField()),
                ('load_out_lighting', models.DateTimeField(blank=True, null=True)),
                ('load_out_sound', models.DateTimeField(blank=True, null=True)),
                ('day_of_show_notes', models.TextField(blank=True)),
                ('archived', models.BooleanField(default=False)),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='client.orgcontact')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('L', 'Lighting'), ('S', 'Sound'), ('M', 'Manager'), ('O', 'Other')], max_length=1)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('gig', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gig.gig')),
            ],
        ),
        migrations.CreateModel(
            name='SystemInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rented_for', models.DurationField()),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gig.gig')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipment.system')),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_in', models.DateTimeField()),
                ('time_out', models.DateTimeField()),
                ('processed', models.BooleanField(default=False)),
                ('contested', models.BooleanField(default=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gig.job')),
            ],
        ),
        migrations.CreateModel(
            name='JobInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gig.job')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='linked_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gig.systeminstance'),
        ),
        migrations.AddField(
            model_name='gig',
            name='employees',
            field=models.ManyToManyField(through='gig.Job', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gig',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='location.location'),
        ),
        migrations.AddField(
            model_name='gig',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client.organization'),
        ),
        migrations.AddField(
            model_name='gig',
            name='systems',
            field=models.ManyToManyField(through='gig.SystemInstance', to='equipment.System'),
        ),
    ]
