# Generated by Django 3.2 on 2021-05-06 01:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("equipment", "0001_initial"),
        ("client", "0001_initial"),
        ("auth", "0001_initial"),
        ("location", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AddonInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qty", models.IntegerField(default=1)),
                (
                    "addon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="equipment.systemaddon",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Gig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("notes", tinymce.models.HTMLField(blank=True, null=True)),
                ("setup_by", models.DateTimeField(verbose_name="Setup By")),
                ("start", models.DateTimeField(verbose_name="Gig start time")),
                ("end", models.DateTimeField(verbose_name="Gig end time")),
                ("day_of_show_notes", models.TextField(blank=True)),
                ("archived", models.BooleanField(default=False)),
                ("published", models.BooleanField(default=False)),
                (
                    "contact",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="client.orgcontact",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="location.location",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="client.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("L", "Lighting"),
                            ("S", "Sound"),
                            ("M", "Manager"),
                            ("O", "Other"),
                            ("T", "Staging"),
                        ],
                        max_length=1,
                    ),
                ),
                ("is_test", models.BooleanField(default=False)),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "gig",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="gig.gig"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SystemInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "addons",
                    models.ManyToManyField(
                        blank=True,
                        through="gig.AddonInstance",
                        to="equipment.SystemAddon",
                    ),
                ),
                (
                    "employees",
                    models.ManyToManyField(
                        through="gig.Job", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "gig",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="gig.gig"
                    ),
                ),
                (
                    "system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="equipment.system",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rented Systems",
            },
        ),
        migrations.CreateModel(
            name="LoadIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("L", "Lighting"),
                            ("S", "Sound"),
                            ("M", "Manager"),
                            ("O", "Other"),
                            ("T", "Staging"),
                        ],
                        max_length=1,
                    ),
                ),
                ("shop_time", models.DateTimeField()),
                ("load_in", models.DateTimeField()),
                ("load_out", models.DateTimeField()),
                (
                    "gig",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="gig.gig"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobInterest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submitted", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="gig.job"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="job",
            name="linked_system",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="gig.systeminstance",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="position",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="auth.group"
            ),
        ),
        migrations.AddField(
            model_name="gig",
            name="systems",
            field=models.ManyToManyField(
                through="gig.SystemInstance", to="equipment.System"
            ),
        ),
        migrations.AddField(
            model_name="addoninstance",
            name="systemInstance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="gig.systeminstance"
            ),
        ),
    ]
