# Generated by Django 3.2 on 2021-04-13 02:45

from django.conf import settings
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gig', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gig',
            name='employees',
        ),
        migrations.AddField(
            model_name='systeminstance',
            name='employees',
            field=models.ManyToManyField(through='gig.Job', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gig',
            name='end',
            field=models.DateTimeField(verbose_name='Gig end time'),
        ),
        migrations.AlterField(
            model_name='gig',
            name='notes',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='systeminstance',
            name='rented_for',
            field=models.DurationField(verbose_name='# Hours rented'),
        ),
    ]
