# Generated by Django 3.2.2 on 2021-05-11 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0002_alter_addoninstance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systeminstance',
            options={'verbose_name': 'Rented System', 'verbose_name_plural': 'Rented Systems'},
        ),
    ]
