# Generated by Django 3.2 on 2021-04-21 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_fee_invoice_shift'),
        ('gig', '0002_auto_20210412_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='shifts',
            field=models.ManyToManyField(to='finance.Shift'),
        ),
        migrations.DeleteModel(
            name='Shift',
        ),
    ]
