# Generated by Django 3.2 on 2021-04-21 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0003_auto_20210420_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('L', 'Lighting'), ('S', 'Sound'), ('M', 'Manager'), ('O', 'Other'), ('T', 'Staging')], max_length=1)),
                ('load_in', models.DateTimeField(blank=True, null=True)),
                ('load_out', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='gig',
            name='load_in_lighting',
        ),
        migrations.RemoveField(
            model_name='gig',
            name='load_in_sound',
        ),
        migrations.RemoveField(
            model_name='gig',
            name='load_out_lighting',
        ),
        migrations.RemoveField(
            model_name='gig',
            name='load_out_sound',
        ),
        migrations.AlterField(
            model_name='job',
            name='department',
            field=models.CharField(choices=[('L', 'Lighting'), ('S', 'Sound'), ('M', 'Manager'), ('O', 'Other'), ('T', 'Staging')], max_length=1),
        ),
        migrations.AddField(
            model_name='gig',
            name='load_ins',
            field=models.ManyToManyField(to='gig.LoadIn'),
        ),
    ]
