# Generated by Django 3.2 on 2021-04-21 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gig', '0004_auto_20210420_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gig',
            name='load_ins',
        ),
        migrations.AddField(
            model_name='loadin',
            name='gig',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gig.gig'),
            preserve_default=False,
        ),
    ]
