# Generated by Django 3.2 on 2021-04-21 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='department',
            field=models.CharField(choices=[('L', 'Lighting'), ('S', 'Sound'), ('M', 'Manager'), ('O', 'Other'), ('T', 'Staging')], max_length=1),
        ),
    ]
