# Generated by Django 3.2 on 2021-05-06 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0002_group_hourly_rate"),
        ("employee", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="officehours",
            name="position",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.PROTECT, to="auth.group"
            ),
        ),
    ]
