# Generated by Django 3.2 on 2021-04-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="is_admin",
        ),
        migrations.AlterField(
            model_name="employee",
            name="is_superuser",
            field=models.BooleanField(default=False, verbose_name="System Admin"),
        ),
    ]
