# Generated by Django 3.2 on 2021-05-06 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0002_group_hourly_rate"),
        ("employee", "0002_officehours_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="officehours",
            name="position",
            field=models.ForeignKey(
                default=18, on_delete=django.db.models.deletion.PROTECT, to="auth.group"
            ),
        ),
    ]
