# Generated by Django 3.2 on 2021-05-06 01:18

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="onboardingStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_open", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="signupStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_open", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("message", tinymce.models.HTMLField()),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("normal bg-white text-black", "Normal"),
                            ("bg-green-500", "Success"),
                            ("bg-yellow-500", "Warning"),
                            ("bg-red-500", "Danger/Error"),
                        ],
                        default="normal",
                        max_length=64,
                    ),
                ),
                ("date_published", models.DateTimeField(auto_now_add=True)),
                (
                    "groups_to_send_to",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Send the notification to the following groups.",
                        to="auth.Group",
                    ),
                ),
            ],
        ),
    ]
