# Generated by Django 3.2 on 2021-04-12 19:34

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="message",
            field=tinymce.models.HTMLField(),
        ),
    ]
