# Generated by Django 3.2 on 2021-04-21 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_signupstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='onboardingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField()),
            ],
        ),
    ]
