# Generated by Django 3.2.2 on 2021-08-12 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        ('location', '__first__'),
        ('auth', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(default='New Hire', on_delete=django.db.models.deletion.PROTECT, to='auth.group', to_field='name')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('submitted', models.DateTimeField(auto_now_add=True)),
                ('answered', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('systems', models.ManyToManyField(blank=True, to='equipment.System')),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('dept', models.CharField(choices=[('L', 'Lighting'), ('S', 'Sound'), ('M', 'Manager'), ('O', 'Other'), ('T', 'Staging')], max_length=1)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('notes', tinymce.models.HTMLField(blank=True, null=True)),
                ('attendees', models.ManyToManyField(blank=True, related_name='attendees', through='training.Trainee', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.location')),
                ('systems', models.ManyToManyField(blank=True, to='equipment.System')),
                ('trainers', models.ManyToManyField(related_name='trainers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='trainee',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.training'),
        ),
    ]
