# Generated by Django 3.2.2 on 2021-05-11 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0013_merge_20210511_1218'),
        ('training', '0002_alter_trainee_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='position',
            field=models.ForeignKey(default='New Hire', on_delete=django.db.models.deletion.PROTECT, to='auth.group', to_field='name'),
        ),
    ]
